ALTER TABLE venues
DROP COLUMN IF EXISTS owner_name,
DROP COLUMN IF EXISTS owner_nik,
DROP COLUMN IF EXISTS province,
DROP COLUMN IF EXISTS city,
DROP COLUMN IF EXISTS district,
DROP COLUMN IF EXISTS village,
DROP COLUMN IF EXISTS postal_code;
